### ISSUE TITLE
Configurações

### ISSUE THREAD

**Issue by rafaelsabino** [vmarcosp/covidbr-app#11]
Bom dia, o que seria preciso para este app funcionar em uma página da web? Tem alguma configuração específica? 
Não conheço bem como manipular extensões .tsx

**Comment by iagolaguna** [comment]
Bom dia @rafaelsabino o app já funciona em página web, segue o link https://covidbr.netlify.com/

**Comment by rafaelsabino** [comment]
Boa noite, não consegui fazer funcionar, infelizmente. É um excelente mapa.

**Comment by vmarcosp** [comment]
opa fala @rafaelsabino tudo certo? Tu deu uma olhadinha no passos do readme? Tem que ter o NodeJS instalado juntamente com npm

**Comment by rafaelsabino** [comment]
Tudo certo parceiro, sim eu olhei mas estou apanhando nos comandos para executar o projeto que já é existente. Não estou conseguindo definir no Node como fazer pra iniciar este projeto localmente.

**Comment by rafaelsabino** [comment]
Eu consigo compilar, instalar os pacotes necessários. mas não estou conseguindo rodar em localhost

C:\Users\Avell\COVID_BR>npm run build

> covidbr-app@1.0.0 build C:\Users\Avell\COVID_BR
> cross-env NODE_ENV=production parcel build public/index.html --no-source-maps

√  Built in 9.06s.

dist\src.0a4c7fb5.js               974.66 KB    8.66s
dist\alliance-logo.9125b389.svg     16.85 KB    665ms
dist\512.69637f4f.png               15.17 KB    519ms
dist\src.550334a0.css               10.59 KB    3.43s
dist\192.be220ad7.png                 5.5 KB    886ms
dist\logo.ce23ed75.svg               4.69 KB    666ms
dist\marker-icon.b29b8023.png        1.43 KB    1.15s
dist\layers-2x.d8c4f271.png          1.23 KB    1.14s
dist\city-pin.11d37de9.svg           1.14 KB    427ms
dist\state-pin.b9896bfb.svg          1.13 KB    749ms
dist\favicon.5cfda9a6.ico            1.12 KB    887ms
dist\index.html                      1.08 KB    330ms
dist\layers.350ec81b.png               696 B    738ms
dist\pin-icon.67a880cd.svg             365 B    541ms
dist\manifest.webmanifest              358 B    376ms
dist\arrow.faec403a.svg                230 B    363ms

C:\Users\Avell\COVID_BR>npm start
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Avell\AppData\Roaming\npm-cache\_logs\2020-04-03T02_37_19_488Z-debug.log

------
O comando está correto ou estou fazendo errado?

**Comment by iagolaguna** [comment]
@rafaelsabino  se você olhar o package.json na parte de "scripts"
```
"scripts": {
    "dev": "cross-env PARCEL_AUTOINSTALL=false parcel public/index.html",
    "build": "cross-env NODE_ENV=production parcel build public/index.html --no-source-maps",
    "linter": "eslint --fix src/**/*.ts src/**/*.tsx",
    "test": "jest --verbose",
    "test:coverage": "yarn test --coverage && jest-coverage-badges --output './badges'"
  }
```
hoje não existe um comando pra levantar o build gerado  do projeto mas acredito que você poderia usar, para visualizar o build
```
http-server ./dist 
```
Porém eu sugiro que você suba o app com o comando `npm run dev`, que o hot reload vai estar ativado e você podera ver automaticamente qualquer alteração que você fizer sem precisar rodar o comando build para ver as alterações que foram feitas.

**Comment by rafaelsabino** [comment]
@iagolaguna muito obrigado pelas informações, eu fiz exatamente conforme script e oq vc passou porém tanto o build gerado quanto o modo .dev carregam o mapa, imagens, tudo, menos os dados. Tanto localmente quanto na web os dados não mostram. Ficam tudo em branco. 

Na depuração aparece ser um erro de graphql não sei onde é o erro ao gerar os mesmos dados que vocês no link do site. Gostaria de subir pra divulgar aqui na minha cidade este excelente mapa, infelizmente estou apanhando pra exibir corretamente.

**Comment by rafaelsabino** [comment]
Conforme dito na resposta anterior eu baixei novamente os dados para começar do zero. 
Então instalei os pacotes e dei o comando `npm run dev` porém quando carrega a página sobe sem dados. Igual na imagem em anexo. Sabem o motivo?

![Anotação 2020-04-03 092631](https://user-images.githubusercontent.com/12975702/78360647-81fe8100-758d-11ea-908e-b8db3ee95348.png)

**Comment by vmarcosp** [comment]
Ah certo @rafaelsabino faltou incluir na verdade, como apontar para a API na documentação, irei incluir. Você pode fazer de duas formas para obter os dados:
- Copiar o .env.sample e renomear para .env
  - Alterar o valor de `API_URL` para "http://corona-monitor-api.herokuapp.com"

Ou, você pode baixar o projeto da API que esta neste [repo](https://github.com/vmarcosp/covidbr-api), seguir os passos descritos no README deste repositório e rodar localmente a api no seu ambiente. Se fizer desta forma, basta alterar o `API_URL` do arquivo que ".env" que você criou no projeto do app para "http://localhost:<PORTA_CONFIGURADA>". Este valor "PORTA_CONFIGURADA" está na configuração do .env no repositório da API.

**Comment by rafaelsabino** [comment]
Boa tarde. Muito obrigado pela informação @vmarcosp. Consegui ajustar local. Uma pergunta para que os dados apareça em servidor web tenho que rodar tudo em node no Server ou posso copiar os dados compilados direto para o Server? Eu fiz a cópia pro servidor web mas não está funcionando. Aparece em branco também. Mas localmente está funcionando tudo. Sabe por que da diferença? Ele mapeia caminhos físicos, seria isso?
