### ISSUE TITLE
Grupo do telegram

### ISSUE THREAD

**Issue by dsevero** [vmarcosp/covidbr-app#2]
Boa noite! Poderias divulgar o grupo mencionado abaixo? Talvez possamos ajudar. Eu sou um dos responsáveis pelo https://github.com/3778/COVID-19

"Grupo de Tratamento de Dados do COVID-19 no Telegram - Que mantém os dados atualizados diariamente, independente da plataforma IVIS do Ministério da Saúde"

Caso queira enviar direto, meu Telegram é https://t.me/dsevero

Caso não, entendo perfeitamente. Obrigado!

**Comment by dsevero** [comment]
Caso queira enviar direto, meu Telegram é https://t.me/dsevero

**Comment by vmarcosp** [comment]
Opa fala @dsevero bele? Cara preciso pedir pra eles antes, mas nos falamos pelo telegram pode ser ?
