### ISSUE TITLE
Adicionar porcentagem aos gráficos

### ISSUE THREAD

**Issue by vmarcosp** [vmarcosp/covidbr-app#3]
Adicionar porcentagem aos gráficos do app

**Comment by biewxw** [comment]
Olá @vmarcosp, estou implementando essa melhoria e gostaria de saber como acha que a exibição da porcentagem deveria ser feita, dentro ou acima de cada barra?

**Comment by biewxw** [comment]
@vmarcosp mantive a porcentagem acima de cada barra para ser mais legível, dentro delas a visualização ficava um pouco ruim dependendo da cor de background. O PR já está pronto para ser revisado e aberto para possíveis alterações! #14

**Comment by vmarcosp** [comment]
#14
